services:
  api:
    build: .
    container_name: api-orquestador
    ports:
      - "8003:8003"
    restart: unless-stopped
    networks:
      - internal_network
    environment:
      API_USUARIOS : http://api-usuarios:8000
      API_FACTURAS : http://api-factura:8002
      API_PRODUCTOS : http://api-productos:8001

networks:
  internal_network:
    external: true